const nutritionGroups = [
  {
    id: "proteiness",
    label: "Protéines",
    children: [
      { key: "tryptophane", label: "Tryptophane(g)", value: 0 },
      { key: "threonine", label: "Thréonine(g)", value: 0 },
      { key: "isoleucine", label: "Isoleucine(g)", value: 0 },
      { key: "leucine", label: "Leucine(g)", value: 0 },
      { key: "lysine", label: "Lysine(g)", value: 0 },
      { key: "methionine", label: "Méthionine(g)", value: 0 },
      { key: "cystine", label: "Cystine(g)", value: 0 },
      { key: "phenylalanine", label: "Phénylalanine(g)", value: 0 },
      { key: "tyrosine", label: "Tyrosine(g)", value: 0 },
      { key: "valine", label: "Valine(g)", value: 0 },
      { key: "arginine", label: "Arginine(g)", value: 0 },
      { key: "histidine", label: "Histidine(g)", value: 0 },
      { key: "aspartic_acid", label: "Acide aspartique(g)", value: 0 },
      { key: "glutamic_acid", label: "Acide glutamique(g)", value: 0 },
      { key: "glycine", label: "Glycine(g)", value: 0 },
      { key: "proline", label: "Proline(g)", value: 0 },
      { key: "serine", label: "Sérine(g)", value: 0 },
      { key: "hydroxyproline", label: "Hydroxyproline(g)", value: 0 },
      { key: "total", label: "Total(g)", value: 0 },
    ],
  },
  {
    id: "lipides",
    label: "Lipides",
    children: [
      { key: "tryptophane", label: "Cholestérol(mg)", value: 0 },
      { key: "acides_gras_saturés", label: "Acides gras saturés(g)", value: 0 },
      { key: "acides_gras_polyinsaturés", label: "Acides gras polyinsaturés(g)", value: 0 },
      { key: "acide_oléique", label: "Acide oléique(g)", value: 0 },
      { key: "acide_ruménique", label: "Acide ruménique(g)", value: 0 },
      { key: "acide_arachidonique", label: "Acide arachidonique(g)", value: 0 },
      { key: "acide_linoléique", label: "Acide linoléique(g)", value: 0 },
      { key: "acide_stéaridonique", label: "Acide stéaridonique(g)", value: 0 },
      { key: "acide_docosapentaénoïque", label: "Acide docosapentaénoïque(g)", value: 0 },
      { key: "acide_alpha_linolénique", label: "Acide alpha-linolénique(g)", value: 0 },
      { key: "total", label: "Total(g)", value: 0 },
    ],
  },
  {
    id: "glucides",
    label: "Glucides",
    children: [
      { key: "saccharose", label: "Saccharose(g)", value: 0 },
      { key: "glucose", label: "Glucose(g)", value: 0 },
      { key: "fructose", label: "Fructose(g)", value: 0 },
      { key: "lactose", label: "Lactose(g)", value: 0 },
      { key: "maltose", label: "Maltose(g)", value: 0 },
      { key: "mannitol", label: "Mannitol(g)", value: 0 },
      { key: "sorbitol", label: "Sorbitol(g)", value: 0 },
      { key: "galactose", label: "Galactose(g)", value: 0 },
      { key: "raffinose", label: "Raffinose(g)", value: 0 },
      { key: "stachyose", label: "Stachyose(g)", value: 0 },
      { key: "amidon", label: "Amidon(g)", value: 0 },
      { key: "total", label: "Total(g)", value: 0 },
    ],
  },
  {
    id: "alcool",
    label: "Alcool",
    children: [
      { key: "total", label: "Total(g)", value: 0 },
    ],
  },
  {
    id: "vitamines",
    label: "Vitamines",
    children: [
      { key: "vitamine_d", label: "Vitamine D(mg)", value: 0 },
      { key: "vitamine_c", label: "Vitamine C(mg)", value: 0 },
      { key: "vitamine_b1", label: "Vitamine B1(mg)", value: 0 },
      { key: "vitamine_b2", label: "Vitamine B2(mg)", value: 0 },
      { key: "vitamine_b5", label: "Vitamine B5(mg)", value: 0 },
      { key: "vitamine_b6", label: "Vitamine B6(mg)", value: 0 },
      { key: "vitamine_b12", label: "Vitamine B12(mg)", value: 0 },
      { key: "vitamine_k", label: "Vitamine K(mg)", value: 0 },
      { key: "vitamine_a", label: "Vitamine A(mg)", value: 0 },
      { key: "vitamine_b3", label: "Vitamine B3(mg)", value: 0 },
      { key: "total", label: "Total(mg)", value: 0 },
    ],
  },
  {
    id: "minéraux",
    label: "Minéraux",
    children: [
      { key: "saccharose", label: "Calcium(mg)", value: 0 },
      { key: "glucose", label: "Fer(mg)", value: 0 },
      { key: "fructose", label: "Magnésium(mg)", value: 0 },
      { key: "lactose", label: "Phosphore(mg)", value: 0 },
      { key: "maltose", label: "Potassium(mg)", value: 0 },
      { key: "mannitol", label: "Sodium(mg)", value: 0 },
      { key: "sorbitol", label: "Zinc(mg)", value: 0 },
      { key: "galactose", label: "Cuivre(mg)", value: 0 },
      { key: "raffinose", label: "Manganèse(mg)", value: 0 },
      { key: "stachyose", label: "Sélénium(mg)", value: 0 },
      { key: "total", label: "Total(mg)", value: 0 },
    ],
  },
  {
    id: "eau",
    label: "Eau",
    children: [
      { key: "total", label: "Total(g)", value: 0 },
    ],
  },
  {
    id: "fibres",
    label: "Fibres",
    children: [
      { key: "total", label: "Total(g)", value: 0 },
    ],
  },
  {
    id: "autres_constituants",
    label: "Autres constituants",
    children: [
      { key: "caféine", label: "Caféine(mg)", value: 0 },
      { key: "théobromine", label: "Théobromine(mg)", value: 0 },
      { key: "aspartame", label: "Aspartame(mg)", value: 0 },
      { key: "total", label: "Total(mg)", value: 0 },
    ],
  },
];